# Generated by Django 5.1.7 on 2025-10-21 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('uniquekey', models.CharField(max_length=20, unique=True)),
                ('course', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='studentpages.department')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.studgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Daylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='studentpages.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('fileportfolio', models.BinaryField(editable=True)),
                ('description', models.TextField()),
                ('studentportowner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='studentpages.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.studgroup'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('task', models.BinaryField(editable=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.lesson')),
                ('studgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.studgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Taskanswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesanswer', models.BinaryField(editable=True)),
                ('mark', models.IntegerField()),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.task')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('departments', models.ManyToManyField(related_name='teachers', to='studentpages.department')),
                ('fkuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.user')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='studentpages.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentpages.user'),
        ),
    ]
