# Generated by Django 5.1.7 on 2025-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='uslog',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='fileportfolio',
            field=models.FileField(upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.FileField(upload_to='tasks/'),
        ),
        migrations.AlterField(
            model_name='taskanswer',
            name='filesanswer',
            field=models.FileField(upload_to='taskanswers/'),
        ),
    ]
