from .daylist import Daylist
from .lesson import Lesson
from .portfolio import Portfolio
from .student import Student
from .studgroup import Studgroup
from .department import Department
from .task import Task
from .taskanswer import Taskanswer
from .teacher import Teacher
from .user import User